services:
  backend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - "${BACKEND_SOURCE}:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development

  frontend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - "${FRONTEND_SOURCE}:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
